/**
 * JWTToken_Auth_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type RequestStatus = 2 | 4 | 6 | 7;

export const RequestStatus = {
    NUMBER_2: 2 as RequestStatus,
    NUMBER_4: 4 as RequestStatus,
    NUMBER_6: 6 as RequestStatus,
    NUMBER_7: 7 as RequestStatus
};

