/**
 * JWTToken_Auth_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IntentionDto } from './intentionDto';
import { RequestStatus } from './requestStatus';


export interface RequestDto { 
    id?: number;
    name?: string | null;
    code?: string | null;
    intentions?: Array<IntentionDto> | null;
    status?: RequestStatus;
    userId?: string | null;
    cityId?: number | null;
    requestStatus?: RequestStatus;
}
export namespace RequestDto {
}


